---
sites:
  wordpress-default:
    #don't use a remote repo for provisioning,
    #because of the domain prefix (oldphp-) we'll provide the provision dir locally
    #repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - oldphp-local.wordpress.test

  # wordpress-develop:
  #   #don't use a remote repo for provisioning,
  #   #because of the domain prefix (oldphp-) we'll provide the provision dir locally
  #   #repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
  #   hosts:
  #     - oldphp-src.wordpress-develop.test
  #     - oldphp-build.wordpress-develop.test

  #wordpress-trunk: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-trunk.git
  #multisite: https://github.com/Varying-Vagrant-Vagrants/vvv-multisite.git
  #wordpress-meta-environment: https://github.com/WordPress/meta-environment.git

utilities:
  core:
    - memcached-admin
#    - opcache-status
#    - phpmyadmin <- will use a phpadmin compatible with our php 5.3.x version (see custom section below)
#    - webgrind

  custom:
    - phpmyadmin
